Vagrant.configure("2") do |config|
  # Определяем настройки VM
  config.vm.define "manager01" do |manager|
    manager.vm.box = "ubuntu/focal64"
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.50.10"
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    manager.vm.synced_folder "C:/Users/Sandra/DevOps_7-1/src/part3", "/vagrant"
    manager.vm.provision "shell", path: "C:/Users/Sandra/DevOps_7-1/src/part3/swarm_manager.sh"
    manager.vm.provision "file", source: "C:/Users/Sandra/DevOps_7-1/src/part3/docker-compose.yml", destination: "/home/vagrant/docker-compose.yml"
    manager.vm.provision "file", source: "C:/Users/Sandra/DevOps_7-1/src/services/nginx-service/sites-enabled", destination: "/home/vagrant/"
    manager.vm.provision "file", source: "C:/Users/Sandra/DevOps_7-1/src/services/nginx-service/nginx.conf", destination: "/home/vagrant/"

  end

  config.vm.define "worker01" do |worker1|
    worker1.vm.box = "ubuntu/focal64"
    worker1.vm.hostname = "worker01"
    worker1.vm.network "private_network", ip: "192.168.50.11"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker1.vm.provision "shell", path: "C:/Users/Sandra/DevOps_7-1/src/part3/docker_worker.sh"

    worker1.vm.synced_folder "C:/Users/Sandra/DevOps_7-1/src/part3", "/vagrant"
  end

  config.vm.define "worker02" do |worker2|
    worker2.vm.box = "ubuntu/focal64"
    worker2.vm.hostname = "worker02"
    worker2.vm.network "private_network", ip: "192.168.50.12"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    worker2.vm.provision "shell", path: "C:/Users/Sandra/DevOps_7-1/src/part3/docker_worker.sh"

    worker2.vm.synced_folder "C:/Users/Sandra/DevOps_7-1/src/part3", "/vagrant"
  end
end